In [4]:
import pandas as pd

data1 = pd.read_csv ('train.csv')
data2 = pd.read_csv ('test.csv')

a=pd.concat([data1,data2])
#a.to_csv("titanic_combined.csv")
data2 = pd.read_csv ('titanic_combined.csv')
data2
x=data2.iloc[:,[1,3,4,6,7,8,9,10]].values
y=data2.iloc[:,[11,1]].values
print(x,y)
#x1 = np.delete(y, 1, 1)  # delete second column of C
#print(x1)
data2

E:\ANACONDA3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  


[[22.0 'S' 7.25 ... 3 'male' 1]
 [38.0 'C' 71.2833 ... 1 'female' 1]
 [26.0 'S' 7.925 ... 3 'female' 0]
 ...
 [38.5 'S' 7.25 ... 3 'male' 0]
 [nan 'S' 8.05 ... 3 'male' 0]
 [nan 'C' 22.3583 ... 3 'male' 1]] [[ 0.  22. ]
 [ 1.  38. ]
 [ 1.  26. ]
 ...
 [ nan 38.5]
 [ nan  nan]
 [ nan  nan]]


Unnamed: 0   Age        Cabin Embarked      Fare  \
0              0  22.0          NaN        S    7.2500   
1              1  38.0          C85        C   71.2833   
2              2  26.0          NaN        S    7.9250   
3              3  35.0         C123        S   53.1000   
4              4  35.0          NaN        S    8.0500   
5              5   NaN          NaN        Q    8.4583   
6              6  54.0          E46        S   51.8625   
7              7   2.0          NaN        S   21.0750   
8              8  27.0          NaN        S   11.1333   
9              9  14.0          NaN        C   30.0708   
10            10   4.0           G6        S   16.7000   
11            11  58.0         C103        S   26.5500   
12            12  20.0          NaN        S    8.0500   
13            13  39.0          NaN        S   31.2750   
14            14  14.0          NaN        S    7.8542   
15            15  55.0          NaN        S   16.0000   
16            16   2.0          NaN        Q   29.1250   
17            17   NaN          NaN        S   13.0000   
18            18  31.0          NaN        S   18.0000   
19            19   NaN          NaN        C    7.2250   
20            20  35.0          NaN        S   26.0000   
21            21  34.0          D56        S   13.0000   
22            22  15.0          NaN        Q    8.0292   
23            23  28.0           A6        S   35.5000   
24            24   8.0          NaN        S   21.0750   
25            25  38.0          NaN        S   31.3875   
26            26   NaN          NaN        C    7.2250   
27            27  19.0  C23 C25 C27        S  263.0000   
28            28   NaN          NaN        Q    7.8792   
29            29   NaN          NaN        S    7.8958   
...          ...   ...          ...      ...       ...   
1279         388  21.0          NaN        Q    7.7500   
1280         389   6.0          NaN        S   21.0750   
1281         390  23.0          B24        S   93.5000   
1282         391  51.0          D28        S   39.4000   
1283         392  13.0          NaN        S   20.2500   
1284         393  47.0          NaN        S   10.5000   
1285         394  29.0          NaN        S   22.0250   
1286         395  18.0          C31        S   60.0000   
1287         396  24.0          NaN        Q    7.2500   
1288         397  48.0          B41        C   79.2000   
1289         398  22.0          NaN        S    7.7750   
1290         399  31.0          NaN        Q    7.7333   
1291         400  30.0           C7        S  164.8667   
1292         401  38.0          NaN        S   21.0000   
1293         402  22.0          NaN        C   59.4000   
1294         403  17.0          NaN        S   47.1000   
1295         404  43.0          D40        C   27.7208   
1296         405  20.0          D38        C   13.8625   
1297         406  23.0          NaN        S   10.5000   
1298         407  50.0          C80        C  211.5000   
1299         408   NaN          NaN        Q    7.7208   
1300         409   3.0          NaN        S   13.7750   
1301         410   NaN          NaN        Q    7.7500   
1302         411  37.0          C78        Q   90.0000   
1303         412  28.0          NaN        S    7.7750   
1304         413   NaN          NaN        S    8.0500   
1305         414  39.0         C105        C  108.9000   
1306         415  38.5          NaN        S    7.2500   
1307         416   NaN          NaN        S    8.0500   
1308         417   NaN          NaN        C   22.3583   

                                                   Name  Parch  PassengerId  \
0                               Braund, Mr. Owen Harris      0            1   
1     Cumings, Mrs. John Bradley (Florence Briggs Th...      0            2   
2                                Heikkinen, Miss. Laina      0            3   
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)      0            4   
4             

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt   #pyplot is a module inside matplotlib
from sklearn import metrics
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.preprocessing import Imputer
y1 = Imputer (missing_values='NaN',strategy ='median' , axis=0)
y1 = y1.fit(y[:,[0,1]])
y[:,[0,1]] = y1.transform(y[:,[0,1]])
#print(y)
y2 = np.delete(y, 1, 1) 
print(y2)
x1 = Imputer (missing_values='NaN',strategy ='median' , axis=0)
x1 = x1.fit(x[:,[0,2]])
x[:,[0,2]] = x1.transform(x[:,[0,2]])
print(y)
from sklearn.preprocessing import LabelEncoder

x_encoder =LabelEncoder()

x[:,6]=x_encoder.fit_transform(x[:,6])


from sklearn.preprocessing import LabelEncoder

x_encoder =LabelEncoder()

x[:,1]=x_encoder.fit_transform(x[:,1])
print(x)



[[0.]
 [1.]
 [1.]
 ...
 [0.]
 [0.]
 [0.]]
[[ 0.  22. ]
 [ 1.  38. ]
 [ 1.  26. ]
 ...
 [ 0.  38.5]
 [ 0.  28. ]
 [ 0.  28. ]]
[[22.0 2 7.25 ... 3 1 1]
 [38.0 0 71.2833 ... 1 0 1]
 [26.0 2 7.925 ... 3 0 0]
 ...
 [38.5 2 7.25 ... 3 1 0]
 [28.0 2 8.05 ... 3 1 0]
 [28.0 0 22.3583 ... 3 1 1]]


In [9]:
from sklearn.cross_validation import train_test_split
x_train, x_test, y_train, y_test = train_test_split (x, y2, test_size = 1/3, 
                                                     random_state = 0)
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression (random_state = 0)
LR.fit (x_train, y_train)
print(LR.score (x_train, y_train))

prediction = LR.predict (x_test)
print("RMSE is:-") 
print(np.sqrt(metrics.mean_squared_error(y_test, prediction)))
from sklearn.metrics import accuracy_score
print(accuracy_score(prediction, y_test))
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predicted)

0.8256880733944955
RMSE is:-
0.38862546015894645
0.8489702517162472


E:\ANACONDA3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[288,  22],
       [ 35,  92]], dtype=int64)

In [8]:
from sklearn.cross_validation import train_test_split
x_train, x_test, y_train, y_test = train_test_split (x, y2, test_size = 1/3, 
                                                     random_state = 0)
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(criterion='gini')
model.fit(x_train, y_train)
print(model.score(x_train, y_train))
#Predict Output
predicted= model.predict(x_test)
print("RMSE is:-") 
print(np.sqrt(metrics.mean_squared_error(y_test, predicted)))

from sklearn.metrics import accuracy_score
print(accuracy_score(prediction, y_test))
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predicted)

1.0
RMSE is:-
0.3611575592573076
0.8489702517162472


array([[288,  22],
       [ 35,  92]], dtype=int64)